[package]
name = "certs"
version = "0.1.0"
edition = "2021"

[lib]
name = "libcerts"
path = "src/lib.rs"

[[bin]]
name = "certs"
path = "src/bin/main.rs"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
